import { useEffect, useState } from 'react';
import { KeyPoints } from './KeyPoints';
import { ThemesTags } from './ThemesTags';
import { SourceCard } from './SourceCard';
import './ResearchReport.css';

export function ResearchReport({ data }) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = () => {
    const markdown = generateMarkdown(data);
    navigator.clipboard.writeText(markdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const generateMarkdown = (data) => {
    return `# Research Report: ${data.query}

## Summary
${data.summary}

## Key Points
${data.key_points.map((point, i) => `${i + 1}. ${point}`).join('\n')}

## Key Themes
${data.themes.map(theme => `- #${theme}`).join('\n')}

## Sources
${data.sources.map(source => `- [${source.title}](${source.url})`).join('\n')}

---
Generated by Autonomous Research Assistant
Processing time: ${data.processing_time?.toFixed(2)}s
`;
  };

  return (
    <div className="research-report-container">
      <div className="report-header">
        <h1 className="report-title">Research Report</h1>
        <p className="report-query">{data.query}</p>
        <button className="copy-button" onClick={copyToClipboard}>
          {copied ? '✓ Copied!' : '📋 Copy Report'}
        </button>
      </div>

      <div className="report-content">
        {/* Summary Section */}
        <section className="summary-section card">
          <h2 className="section-title">Summary</h2>
          <div className="summary-text">
            {data.summary.split('\n\n').map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
          </div>
        </section>

        {/* Key Information Section */}
        <div className="grid-2">
          <section className="card">
            <KeyPoints points={data.key_points} />
          </section>

          <section className="card">
            <ThemesTags themes={data.themes} />
          </section>
        </div>

        {/* Sources Section */}
        <section className="sources-section">
          <h2 className="section-title">Sources ({data.sources.length})</h2>
          <div className="sources-grid">
            {data.sources.map((source, index) => (
              <SourceCard key={index} source={source} index={index} />
            ))}
          </div>
        </section>

        {/* Stats Section */}
        <section className="stats-section card">
          <h2 className="section-title">Report Stats</h2>
          <div className="stats-grid">
            <div className="stat">
              <span className="stat-label">Processing Time</span>
              <span className="stat-value">{data.processing_time?.toFixed(2)}s</span>
            </div>
            <div className="stat">
              <span className="stat-label">Sources Analyzed</span>
              <span className="stat-value">{data.sources.length}</span>
            </div>
            <div className="stat">
              <span className="stat-label">Key Points</span>
              <span className="stat-value">{data.key_points.length}</span>
            </div>
            <div className="stat">
              <span className="stat-label">Themes Identified</span>
              <span className="stat-value">{data.themes.length}</span>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
